name: terraform-deploy

on:
  push:
    branches: ["main", "master"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-dev:
    name: Terraform Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::183817605627:role/terraform-deployment-role
          aws-region: us-east-1
          role-session-name: terraform-dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: terraform init

      - name: Select Dev Workspace
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve


  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: terraform-dev
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::183817605627:role/terraform-deployment-role
          aws-region: us-east-1
          role-session-name: terraform-test

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: terraform init

      - name: Select Test Workspace
        run: |
          terraform workspace select test || terraform workspace new test

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve


  terraform-prod:
    name: Terraform Prod
    runs-on: ubuntu-latest
    needs: terraform-test
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::183817605627:role/terraform-deployment-role
          aws-region: us-east-1
          role-session-name: terraform-prod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: terraform init

      - name: Select Prod Workspace
        run: |
          terraform workspace select prod || terraform workspace new prod

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve