name: terraform-deploy

on:
  push:
    branches: ["main", "master"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-dev:
    name: Terraform Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::183817605627:role/terraform-deployment-role
          aws-region: us-east-1
          role-session-name: terraform-dev

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: terraform init

      - name: Select Dev Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Dev)
        run: terraform plan -no-color -var-file=dev.tfvars

      - name: Terraform Apply (Dev)
        run: terraform apply -auto-approve -var-file=dev.tfvars


  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: terraform-dev
    environment: test

    steps:
      - uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::183817605627:role/terraform-deployment-role
          aws-region: us-east-1
          role-session-name: terraform-test

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: terraform init

      - name: Select Test Workspace
        run: terraform workspace select test || terraform workspace new test

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Test)
        run: terraform plan -no-color -var-file=test.tfvars

      - name: Terraform Apply (Test)
        run: terraform apply -auto-approve -var-file=test.tfvars


  terraform-prod:
    name: Terraform Prod
    runs-on: ubuntu-latest
    needs: terraform-test
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::183817605627:role/terraform-deployment-role
          aws-region: us-east-1
          role-session-name: terraform-prod

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.5

      - name: Terraform Init
        run: terraform init

      - name: Select Prod Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Prod)
        run: terraform plan -no-color -var-file=prod.tfvars

      - name: Terraform Apply (Prod)
        run: terraform apply -auto-approve -var-file=prod.tfvars
